### ISSUE TITLE
Service Unavailable 

### ISSUE THREAD

**Issue by Vy03** [spring-petclinic/spring-petclinic-microservices#293]
Hello, I was wondering why it said service unavailable (503) for the services connected to api-gateway? I tried running it locally and it was working just fine a few days ago. I didn't make any changes to the code. This is the error from the api-gateway.

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
TypeError: Cannot read properties of undefined (reading 'map')
    at responseError (httpErrorHandlingInterceptor.js:11:59)
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at k (angular.js:13473:36)
    at v (angular.js:13730:7)
    at XMLHttpRequest.<anonymous> (angular.js:13635:9) 'Possibly unhandled rejection: {}'
```

This is the log from api-gateway container:
```
2024-11-29 11:01:46 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9411
2024-11-29 11:01:46 Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
2024-11-29 11:27:41 2024-11-29T04:27:41.706Z  WARN 1 --- [api-gateway] [     parallel-7] [                                                 ] eactorLoadBalancerExchangeFilterFunction : LoadBalancer does not contain an instance for the service 5add73db10cd
2024-11-29 11:27:55 2024-11-29T04:27:55.321Z  WARN 1 --- [api-gateway] [     parallel-4] [                                                 ] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 119056b056bf
2024-11-29 11:27:55 2024-11-29T04:27:55.322Z  WARN 1 --- [api-gateway] [     parallel-4] [                                                 ] eactorLoadBalancerExchangeFilterFunction : LoadBalancer does not contain an instance for the service 119056b056bf
```

I made sure that all the services are running in the Eureka and every container are running in my Docker. I used different devices and it still shows the same error. Can anyone help to resolve this problem? Any help will be greatly appreciated.

**Comment by arey** [comment]
Hi @Vy03, five days ago, I've merged this PR: https://github.com/spring-petclinic/spring-petclinic-microservices-config/pull/22 
To ensure that this is not a regression, could you please clone this repo, revert the last commit then reference it in your microservices?

**Comment by arey** [comment]
I've done the test and I have the same issue.
```
api-gateway        | 2024-11-29T07:33:08.800Z  WARN 1 --- [api-gateway] [     parallel-9] [                                                 ] eactorLoadBalancerExchangeFilterFunction : LoadBalancer does not contain an instance for the service a1b204f1e878
api-gateway        | 2024-11-29T07:33:11.341Z  WARN 1 --- [api-gateway] [tor-http-nio-14] [                                                 ] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: customers-service
```
@MarianConstantinMarica I will revert the last merge. Did you try the `loadbalancer` with and without docker?

**Comment by arey** [comment]
@Vy03 I let you test again without any changes from your side.

**Comment by Vy03** [comment]
Hello again! I do apologize for replying late. I tried running it locally in my docker and it seems that the issue has been solved, thank you so much!
