### ISSUE TITLE
Implement OAuth2 Security for microservices

### ISSUE THREAD

**Issue by ScopeSebastian** [spring-petclinic/spring-petclinic-microservices#41]
Since there is a lack of samples on how to secure microservices and this is the most suggested method, it could be a good idea to implement this type of security for communication between microservices and securing them from outside requests

**Comment by mszarlinski** [comment]
I think that incorporating Spring Cloud Security to our project is a natural follow up of what we already have one here. I am only wondering if securing our demo application wound't make it too complicated. I would like to keep this project as simple as possible, helping people to get started with Spring Cloud. Maybe we should create a separate branch for an OAuth2 version? @arey @dsyer

**Comment by ScopeSebastian** [comment]
Agree in keeping the project simple, but would be great to have a branch with the OAuth2 implementation.

**Comment by mszarlinski** [comment]
Would you like to contribute or to leave implementation to someone else? I think we can go with separate branch first and then decide whether to merge secured version to master.

**Comment by ScopeSebastian** [comment]
I would be glad to help as much as I can, but I'm not experienced with oauth2 used in microservices. I wanted to use this as a good base to learn the correct way to implement the service.
I could implement what I know till now and then someone else check for improvements

**Comment by mszarlinski** [comment]
Hi @ScopeSebastian, any update on this? :)

**Comment by pmj0yce** [comment]
I'd be interested in contributing to this and other security related items.  In particular what I would like to add (as individual tutorial branches) is:
	1) Securing microservices secrets with [Hashicorp  Vault](https://www.vaultproject.io/)
	2) OAuth2 authentication
	3) Authorization based on both roles and URL in each service
	4) Authorization in Angular UI (or maybe migrate to React with auth).

FWIW I have experience in each of these in my day job.  What is the process on this project ?  Just go ahead and implement then submit a pull request ?  Something else ...?

**Comment by arey** [comment]
Thank you @pmj0yce for your proposition. 
We could have a secure version in a separate branch you'll be in charge to maintain (synchronize with the master branch).
I propose to keep AngularJS. You may go ahead and submit a PR :)

**Comment by briceamk** [comment]
there is any update about Secure version?

**Comment by arey** [comment]
We are looking for some contributors. @pmj0yce was interested but I we didn't have any news.

**Comment by simrin051** [comment]
Hi @arey / @dsyer 

Can  i take up this issue

**Comment by simrin051** [comment]
@arey / @dsyer 
Can you please brief on what is expected out of this task. I am new to OAuth2 and microservices. Can you please brief on what is expected out of this task so that i can code easily. Please. It is an urgent request.

**Comment by simrin051** [comment]
@arey / @dsyer 

Can you please advice. Please.

**Comment by simrin051** [comment]
@arey / @dsyer 

May i know whether authentication using google or github is needed for this issue. I have started to work on this issue.  Can you please specify the requirements. Please.

**Comment by arey** [comment]
I'm not an expert in microservices security but I think we could use the `Spring Authorization Server` https://www.baeldung.com/spring-security-oauth-auth-server. 
I propose to secure  with a JWT token both the API from the Gateway and the API the 3 microservices : `vets`, `visits` and `customers`. 
Keep in mind that this code shoud live in a separate code.
If it could help, I'm working on the Spring Cloud 2021.0 and Spring Boot 2.6 migration. See https://github.com/spring-petclinic/spring-petclinic-microservices/issues/188

**Comment by simrin051** [comment]
Thanks @arey may i know the username and password configuration. May i know whether i should create signin and signup page or is it just for a single user.

**Comment by simrin051** [comment]
@arey , the authorization should be for a single user or multiple users with signup and login page. Can you please confirm. Please

**Comment by simrin051** [comment]
@arey / @pmj0yce  Can you please confirm

**Comment by simrin051** [comment]
@arey / @dsyer / @pmj0yce  Can you please confirm

**Comment by simrin051** [comment]
@arey / @dsyer / @pmj0yce Can you please confirm. Should i do in memory authentication or database authentication.

**Comment by simrin051** [comment]
Hi @dsyer / @arey 

when i configure spring security for API Gateway, i get the below error message. I removed starter web dependency and i added  javax.xml.bind,javax.servlet dependency still the same error. I am stuck with this from 2 days..Can you please advice. 


Caused by: java.lang.IllegalStateException: StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[] failed to start
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.rethrowDeferredStartupExceptions(TomcatWebServer.java:187)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:126)
        ... 18 common frames omitted

**Comment by 488442** [comment]
Any news?

**Comment by donhuvy** [comment]
A near reference web-app without authentication and authorization. Unbeliveable.

**Comment by arey** [comment]
You're right @donhuvy. We have to propose a secured version.
We could use the [Spring Authorization Server](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/).
Before starting to work on this issue, we have to clearly define the security architecture.

**Comment by donhuvy** [comment]
Thank you for your attention. You can see https://github.com/donhuvy/spring_boot_3_oauth2/ , we base on a video tutorial use Spring Boot 2.x .

**Comment by alexandre-touret** [comment]
Hi @arey 
FYI I created a workshop using the whole spring boot / cloud stack w/ spring authorization server

https://github.com/alexandre-touret/rest-apis-versioning-workshop

https://github.com/alexandre-touret/rest-apis-versioning-solution

If you want I can implement it in this project

**Comment by MarianConstantinMarica** [comment]
It's this still available, if yes, can I work on it?

**Comment by dsyer** [comment]
Please do. My preference would be to add a security layer to the gateway, and make the other apps clients of that (so they need a token and a token relay where appropriate). The auth server could be a Spring Auth Server (so that we control the user ids).

**Comment by alexandre-touret** [comment]
Hi
I did that in a workshop where I put both spring cloud gateway and spring authorization server in place.

You can get [here](https://github.com/alexandre-touret/rest-apis-versioning-solution)

**Comment by AronnoDIU** [comment]
Hi, I’d like to work on this. Could you clarify the expected behavior for OAuth2 Security?

**Comment by vetri15** [comment]
hi @arey , I have worked Oauth2 before , shall i work on this ?

**Comment by arey** [comment]
Hi @vetri15, you can certainly work on this issue.

**Comment by vetri15** [comment]
Hi @arey need some guidance.

I have decided the best course to proceed by adding a Keycloak docker container which will act as authorization server and adding spring security on the gateway server so it only allows requests with JWT. 
is this enough or i shall add an extra authentication microservice using springboot to assign and manage roles in the app itself without this microservice the Role assignment in JWT will be done on the Keycloak UI.

**Comment by dsyer** [comment]
It would be much better to use the Spring Auth Server IMO (there’s a checkbox in start.spring.io).

**Comment by vetri15** [comment]
Okay thanks @dsyer , I will use the spring auth server to implement  OAuth2

**Comment by vetri15** [comment]
Hi @arey,

I completed the backend OAuth2 authentication changes for PetClinic and now need to integrate them with the frontend served by `spring-petclinic-api-gateway`.

Could you confirm which frontend repository is used to generate the static files currently checked in under:

`spring-petclinic-api-gateway/src/main/resources/static`

I am not sure whether it comes from:

- https://github.com/spring-petclinic/spring-petclinic-angular
- https://github.com/spring-petclinic/spring-petclinic-angularjs

Also, when I run `ng build`, the generated output structure is different from the existing structure in the API Gateway `static` folder. Is there a specific build command or copy process used for this project?

**Comment by vetri15** [comment]
> Hi [@arey](https://github.com/arey),
> 
> I completed the backend OAuth2 authentication changes for PetClinic and now need to integrate them with the frontend served by `spring-petclinic-api-gateway`.
> 
> Could you confirm which frontend repository is used to generate the static files currently checked in under:
> 
> `spring-petclinic-api-gateway/src/main/resources/static`
> 
> I am not sure whether it comes from:
> 
> * https://github.com/spring-petclinic/spring-petclinic-angular
> * https://github.com/spring-petclinic/spring-petclinic-angularjs
> 
> Also, when I run `ng build`, the generated output structure is different from the existing structure in the API Gateway `static` folder. Is there a specific build command or copy process used for this project?

Hi @dsyer , can you please help on this one. Once the front end is integrated this app would be oauth2 compatible

**Comment by dsyer** [comment]
I don't think the UI code is built anywhere else. It's just written in Javascript statically. You can edit it in place if that's the case.

**Comment by vetri15** [comment]
@dsyer Thanks for clarifying.

I have mainly worked with Angular so far, and I have not worked much with plain static JavaScript files directly.

My concern is that, in the long run, editing static JavaScript files directly may become difficult to maintain, especially for OAuth2-related behavior such as global auth state, route protection, and attaching bearer tokens to API requests.

Would it make sense to consider moving the UI to a small frontend build process, even if the app remains backend-focused? That could make the frontend easier to structure, test, and regenerate into static assets for the API gateway, while still keeping the final deployment model unchanged.

**Comment by arey** [comment]
Hi @vetri15, I've just replied to your post in the AngularJS discussion thread: https://github.com/spring-petclinic/spring-petclinic-microservices/discussions/521

The `spring-petclinic-angular` and `spring-petclinic-reactjs` projects have their own backend: https://github.com/spring-petclinic/spring-petclinic-rest

I think we need to address these two issues separately: the modernisation of the front-end stack and OIDC/OAuth 2 support.
